### ISSUE TITLE
句子重复率问题

### ISSUE THREAD

**Issue by C1oudust** [hitokoto-osc/hitokoto-api#205]
![a4a2f36c579866aba0c5bfec085ba94](https://user-images.githubusercontent.com/29059054/96850039-f1d04c80-1488-11eb-9739-21d025e2c79e.png)
循环调用数次，重复率有点高。

**Comment by greenhat616** [comment]
先简单确认了下，h 分类目前有 55 句句子。有关随机性的测试稍后提供

**Comment by greenhat616** [comment]
duplicated by #237 91
