### ISSUE TITLE
[FEATURE]需求，可否新增一个根据 uuid 或者 id 查询的请求参数

### ISSUE THREAD

**Issue by xkcoding** [hitokoto-osc/hitokoto-api#230]
目前查看接口文档，存在该参数

返回参数名称 | 描述
-- | --
uuid | 一言唯一标识；可以链接到 https://hitokoto.cn?uuid=[uuid] 查看这个一言的完整信息

期望可以在接口层面新增，比如 https://v1.hitokoto.cn?uuid=[uuid] 或者 https://v1.hitokoto.cn?id=[id] 查看单条数据

感谢你们提供「一言」这样的小而美的 API

**Comment by freejishu** [comment]
可尝试使用 /hitokoto/:uuid 接口。
参考：
https://developer.hitokoto.cn/core/#%E7%AE%80%E4%BB%8B

**Comment by xkcoding** [comment]
我本地测试是通过 docker 搭建的本地镜像，未使用官方 api 地址

发现该接口需要登录获取身份信息之后，再另行调用

本地搭建的场景下，需要先注册，结果发现调用注册接口时，报错
![image](https://user-images.githubusercontent.com/10429917/99234481-8bdca800-282f-11eb-8156-1774c5efbacb.png)

问题：
1. 该接口是否可以通过不需要身份验证直接获取？（估计不行，考虑到接口调用的频率以及安全性）
2. 本地搭建的场景，如何操作？（希望作者给些建议，如果官方不能支持，我尽量自己动手，感谢）

**Comment by freejishu** [comment]
首先，P1中403的原因是【无权限。需要验证邮箱。】
您看起来应该是现注册的账户，所以没有验证邮箱，api权限没有打开，请通过https://hitokoto.cn/验证邮箱后再试。
如果您已经有账户，在后台即可获得该用户的token，位置是 用户中心 - 左侧：用户设置 - 点击令牌 。
具体的api调用方法因为图片不全，故这里给个参考，您可以参考这个完善您的代码。

![image](https://user-images.githubusercontent.com/11630435/99238134-55edf280-2834-11eb-9c0a-c00de9595e72.png)

然后回答问题。
有关Q1：目前考虑安全性和资源分配，我们需要一个用户id来去做甄别。但是请放心，如果是正常请求量的调用不会收到限制。
有关Q2：本地场景需要配置各项配套服务，如上图中您应该是没有配置好邮件调用，您可以详细检查一下配置。另外结合您题目中的需求，建议使用官方的api。

**Comment by greenhat616** [comment]
RT

> 我本地测试是通过 docker 搭建的本地镜像，未使用官方 api 地址
> 
> 发现该接口需要登录获取身份信息之后，再另行调用
> 
> 官方 api 地址请求，获取到 token 之后，报错
> ![image](https://user-images.githubusercontent.com/10429917/99235752-33a6a580-2831-11eb-93ef-12604b07d77e.png)
> 
> 本地搭建的场景下，需要先注册，结果发现调用注册接口时，报错
> ![image](https://user-images.githubusercontent.com/10429917/99234481-8bdca800-282f-11eb-8156-1774c5efbacb.png)
> 
> 问题：
> 
> 1. 该接口是否可以通过不需要身份验证直接获取？（估计不行，考虑到接口调用的频率以及安全性）
> 2. 本地搭建的场景，如何操作？（希望作者给些建议，如果官方不能支持，我尽量自己动手，感谢）

Q1 上面回答过了，这边不赘述
Q2 目前仅开源了语句接口（sentence API），处于出于账户信息安全的目的，因此 `hitokoto.cn` 作为域名的核心API 尚未开源。

**Comment by xkcoding** [comment]
Thanks~
