### ISSUE TITLE
404 异常返回建议屏蔽 stack 堆栈信息

### ISSUE THREAD

**Issue by renxia** [hitokoto-osc/hitokoto-api#340]
![image](https://user-images.githubusercontent.com/2276421/125311622-201ef080-e366-11eb-81f0-3c77034b9be6.png)

如图所示，生产模式下 404 返回信息包含的堆栈信息暴露了程序的具体部署路径，看了一下源码，该位置本身已有记录日志，建议屏蔽该字段，只在开发模式下显示

**Comment by greenhat616** [comment]
closed by #341
