### ISSUE TITLE
建议对请求参数列表增加语句长度的参数控制

### ISSUE THREAD

**Issue by tomato-cc** [hitokoto-osc/hitokoto-api#36]
使用场景：
 目前我把一言应用在小程序中。返回的信息显示在页面底部。
但是多次调用后发现一个问题。有些句子非常的长，这就导致了页面排版出现问题。

建议：
 能否增加一个语句长度的控制。比如
https://v1.hitokoto.cn/?c=f&encode=text?len=5  
就只会返回长度在5以内的文本信息

**Comment by greenhat616** [comment]
`1.5.0-beta.1` 加入了 `max_length` 和 `min_length` 参数用于控制句子长度，由于此版本变更有点大所以没有部署线上。如果方便的话，您可以帮我们测试一下应用。
例如，在配置好 Redis 环境后，使用 Docker 一键启动：
```
docker run \
-v /path/to/your/data/dir:/usr/src/app/data \
--network host \
hitokoto/api
```

P.S 由于最近很忙，Beta 2 得 7 月份才能发布。

**Comment by greenhat616** [comment]
阿，昨天抽空更新了一下，今天发布了 beta2。您可以使用此版测试下看看，看看是不是符合理想：D
