### ISSUE TITLE
能否开放http支持

### ISSUE THREAD

**Issue by BluecityS** [hitokoto-osc/hitokoto-api#370]
https对iot极不友好 对于内存小的单片机来说特吃内存 一言的内容也不是什么机密嘛qwq球球了

**Comment by BluecityS** [comment]
我这边用esp8266的话会有强制重定向😭然后会报错

**Comment by freejishu** [comment]
> 我这边用esp8266的话会有强制重定向😭然后会报错

是HSTS导致的重定向吗？
没查到相关资料，不如详细说明一下？

**Comment by greenhat616** [comment]
@freejishu CDN 有强制重定向吧

**Comment by BluecityS** [comment]
确认不是hsts的问题 应该是cdn的>_<

**Comment by greenhat616** [comment]
移除了 http 302
