### ISSUE TITLE
调用Api时会在浏览器console中报错

### ISSUE THREAD

**Issue by Funqiewei** [hitokoto-osc/hitokoto-api#393]
Uncaught TypeError: Cannot set properties of null (setting 'innerText')
    at hitokoto (v1.hitokoto.cn/:1)
    at v1.hitokoto.cn/:1

虽然可以用但是会经常失灵

**Comment by freejishu** [comment]
可否贴一下详细的代码以及更具体的错误信息？
API似乎没有 :1 这种用法 emmmmmm

**Comment by greenhat616** [comment]
请补充一个能复现的调用示例

**Comment by Funqiewei** [comment]
在vue项目index.html中加入了
`<script src="https://v1.hitokoto.cn/?encode=js&select=%23hitokoto" defer></script>`
![08AJN}K89BP`G)BM36IPU1K](https://user-images.githubusercontent.com/69943668/134641025-4390afd9-ec8a-4c32-bc11-48c8da9b7b71.png)
然后就在对应的页面加了
![image](https://user-images.githubusercontent.com/69943668/134642077-7b1d5607-4030-4b2a-a30f-48d74c287a86.png)
有时候能够调用
![image](https://user-images.githubusercontent.com/69943668/134641482-ecd7ddbf-a423-477e-a1fe-7211f21e8bc5.png)
但是也经常会出现调用失败同时报错
![image](https://user-images.githubusercontent.com/69943668/134641916-0ddabd88-50a5-423c-b82c-f5a941801e0d.png)
😂抱歉我有点小白

**Comment by Funqiewei** [comment]
超级感谢！！！！成功了！！！！
