### ISSUE TITLE
在微信小程序内调用接口403

### ISSUE THREAD

**Issue by 1103442828** [hitokoto-osc/hitokoto-api#525]
这是使用微信请求方法的请求内容，之前都是正常近期才出现这个问题

fetch("https://v1.hitokoto.cn/?max_length=50&charset=utf-8", {
  "headers": {
    "accept": "*/*",
    "authorization": "Bearer",
    "content-type": "application/json",
    "noauth": "[object Boolean]",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "cross-site"
  },
  "referrer": "https://servicewechat.com/wx22ca114d2fa3e2ee/devtools/page-frame.html",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": null,
  "method": "GET",
  "mode": "cors",
  "credentials": "include"
});

**Comment by freejishu** [comment]
附带一下在真实环境中的UA和的referrer，我们排查一下。另微信小程序应该是直接使用用户的ip吧？如果有固定的出口ip也可以附带一下。我们在前几日的构架切换中确实屏蔽了一些网站和ip，但是理论上不影响小程序。
如果担心泄露，可以把信息发送到 [i@loli.online](mailto:i@loli.online) 或 [i@freejishu.com](mailto:i@freejishu.com)。

**Comment by 1103442828** [comment]
> 
"System:" "Android 12, WeChat 8.0.28.2240"

**Comment by 1103442828** [comment]
> 附带一下在真实环境中的UA和的referrer，我们排查一下。另微信小程序应该是直接使用用户的ip吧？如果有固定的出口ip也可以附带一下。我们在前几日的构架切换中确实屏蔽了一些网站和ip，但是理论上不影响小程序。 如果担心泄露，可以把信息发送到 [i@loli.online](mailto:i@loli.online) 或 [i@freejishu.com](mailto:i@freejishu.com)。

"System:" "Android 12, WeChat 8.0.28.2240"
"Network:" "5g"
"UA:" "Mozilla/5.0 (Linux; Android 12; 2106118C Build/SKQ1.211006.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/86.0.4240.99 XWEB/4343 MMWEBSDK/20220903 Mobile Safari/537.36 MMWEBID/1253 MicroMessenger/8.0.28.2240(0x28001C57) WeChat/arm64 Weixin NetType/5G Language/zh_CN ABI/arm64 MiniProgramEnv/android"
"WeChatLib:" "2.27.3 (2022.11.22 23:34:35)"

**Comment by 1103442828** [comment]
> 附带一下在真实环境中的UA和的referrer，我们排查一下。另微信小程序应该是直接使用用户的ip吧？如果有固定的出口ip也可以附带一下。我们在前几日的构架切换中确实屏蔽了一些网站和ip，但是理论上不影响小程序。 如果担心泄露，可以把信息发送到 [i@loli.online](mailto:i@loli.online) 或 [i@freejishu.com](mailto:i@freejishu.com)。
请求都是从每个用户终端发出的应该没有固定ip，因为小程序限制真实环境只能拿到以上的一些数据

**Comment by greenhat616** [comment]
@1103442828 您好，我尝试使用您提供的测试用例，如：
![图片](https://user-images.githubusercontent.com/41122242/203694714-e9cda8d3-2d00-4cc1-a7b6-39478d57e3d7.png)
```js
const fetch = require("node-fetch");

fetch("https://v1.hitokoto.cn/?max_length=50&charset=utf-8", {
  headers: {
    accept: "/",
    authorization: "Bearer",
    "content-type": "application/json",
    noauth: "[object Boolean]",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "cross-site",
  },
  referrer:
    "https://servicewechat.com/wx22ca114d2fa3e2ee/devtools/page-frame.html",
  referrerPolicy: "strict-origin-when-cross-origin",
  body: null,
  method: "GET",
  mode: "cors",
  credentials: "include",
})
  .then((res) => res.json())
  .then(console.log)
  .catch(console.error);
```
测试结果为正常的。
我猜测可能是 IP，或者是 `authorization` 这个字段被 CDN 拦截了？
您可以尝试把 authorization 这个字段从 header 中去除（我们不需要验证此字段），如果再不行的话，您方便进入我们的群组与我们私聊或者直接使用邮件沟通嘛（留下您的 IP 等较为敏感的信息），我们来对此定位一下，是否是 CDN 的拦截行为。

**Comment by 1103442828** [comment]
> @1103442828 您好，我尝试使用您提供的测试用例，如： ![图片](https://user-images.githubusercontent.com/41122242/203694714-e9cda8d3-2d00-4cc1-a7b6-39478d57e3d7.png)
> 
> ```js
> const fetch = require("node-fetch");
> 
> fetch("https://v1.hitokoto.cn/?max_length=50&charset=utf-8", {
>   headers: {
>     accept: "/",
>     authorization: "Bearer",
>     "content-type": "application/json",
>     noauth: "[object Boolean]",
>     "sec-fetch-dest": "empty",
>     "sec-fetch-mode": "cors",
>     "sec-fetch-site": "cross-site",
>   },
>   referrer:
>     "https://servicewechat.com/wx22ca114d2fa3e2ee/devtools/page-frame.html",
>   referrerPolicy: "strict-origin-when-cross-origin",
>   body: null,
>   method: "GET",
>   mode: "cors",
>   credentials: "include",
> })
>   .then((res) => res.json())
>   .then(console.log)
>   .catch(console.error);
> ```
> 
> 测试结果为正常的。 我猜测可能是 IP，或者是 `authorization` 这个字段被 CDN 拦截了？ 您可以尝试把 authorization 这个字段从 header 中去除（我们不需要验证此字段），如果再不行的话，您方便进入我们的群组与我们私聊或者直接使用邮件沟通嘛（留下您的 IP 等较为敏感的信息），我们来对此定位一下，是否是 CDN 的拦截行为。

确实是是因为authorization这个属性，移除后请求成功了 感谢！
