### ISSUE TITLE
是否有英文版的一言

### ISSUE THREAD

**Issue by qinleilxl** [hitokoto-osc/hitokoto-api#537]
是否有英文版的一言

**Comment by greenhat616** [comment]
程序与句集无关。
句集中目前简中的语句占比最大，v1 尚未提供语言选择的功能。
您可以自由部署后，使用自己的句集，句集的结构可以参考：
* https://github.com/hitokoto-osc/sentences-bundle 句子包
* https://github.com/hitokoto-osc/hitokoto-sentence-generator 生成器
