### ISSUE TITLE
encode=text参数不能正常返回数据

### ISSUE THREAD

**Issue by Nicholasjl** [hitokoto-osc/hitokoto-api#59]
rt

**Comment by freejishu** [comment]
可能是bug
因为现在api开发者是 @greenhat616 Api相关实现这边暂时没人能弄了 他本人高三 现在回学校了 所以也一直没法排查 先用其他方法实现一下吧

**Comment by MOUSE123S** [comment]
BUG应位于 `/src/controllers/hitokoto.js `
根据 150 ~ 158 行的代码

**Comment by freejishu** [comment]
这块虽然定位了，但是还是要等藤球回来确认。
很快了，顺祝高考顺利。

**Comment by Nicholasjl** [comment]
@freejishu 
既然暂时解决不了问题就先解决文档吧。祝高考顺利
