### ISSUE TITLE
重构计划

### ISSUE THREAD

**Issue by greenhat616** [hitokoto-osc/hitokoto-api#85]
* [x] 重构控制器模块，使其能生成一张控制器表（自动迭代子目录）
* [x] 重构一言控制器（拆分文件，降低理解难度）
* [x] 重构网易云，拆分多个子控制器文件
  * [x] 使用 NeteaseCloudMusic 替代现有的两个包 
* [x] 将现有的一些配置文件移动到 config/adapter 目录
* [ ] ~web 使用多线程模型（如果可能的话）~ 直接用 Docker 吧，短期不考虑支持。
* [ ] ~解藕模块，为多实例部署做准备~  直接用 Docker 吧，短期不考虑支持。

**Comment by ahkui** [comment]
> web 使用多线程模型

這掛上 `pm2` 應該可以解決

**Comment by greenhat616** [comment]
> > web 使用多线程模型
> 
> 這掛上 `pm2` 應該可以解決

I will have a try. Thank you
