### ISSUE TITLE
接口句子重复概率过大

### ISSUE THREAD

**Issue by XuLin404** [hitokoto-osc/hitokoto-api#91]
使用的接口的时候获取到的句子有很大概率是重复的，未指定分类。一句话在一个小时之内每60s刷新一次的情况下会重复三四次

**Comment by freejishu** [comment]
这块可以先解释一下逻辑
如果没有提交特定的type，按照下列规则选择句子：
1、取随机数1到N（N为type数量），取随机数对应type为本次输出的type；
2、取随机数1到x（x为该type下对应句子的数量），取随机数对应的句子。
在我们使用20线程获取了8w多次句子后，得到了这样一个结果：
![image](https://user-images.githubusercontent.com/11630435/87632875-d4466500-c76c-11ea-8e66-ec85123142c3.png)
标准差为106.8，在可接受的范围之内。
按照前面的算法，我们其实可以算出某一个特定句子被获取到的概率为1/N·x，这样设计的初衷是为了给与类型下句子数量较少的冷门分类提高曝光的机会，但是可能现在提高的有点多。
@greenhat616 建议令N=每个分类赋予单独的权值，从而更好地分配资源。

**Comment by greenhat616** [comment]
我觉得需要更深入得探讨这个问题

**Comment by ZhangSanSanLa** [comment]
取随机数1到x（x为该type下对应句子的数量），取随机数对应的句子。-----
1、当用户随机请求时，type 可以随机函数确定，但x可直接按数据库中存储顺序(假设按uuid排序或其他排序)取，可有效减低重复。(对用户来说，已经按uuid排序的句子也是随机的)
2、根据请求ip建立缓存列表，1000次请求绝不重复。超过1000次重新建立已经请求过的句子列表。

**Comment by greenhat616** [comment]
> 取随机数1到x（x为该type下对应句子的数量），取随机数对应的句子。----- 1、当用户随机请求时，type 可以随机函数确定，但x可直接按数据库中存储顺序(假设按uuid排序或其他排序)取，可有效减低重复。(对用户来说，已经按uuid排序的句子也是随机的) 2、根据请求ip建立缓存列表，1000次请求绝不重复。超过1000次重新建立已经请求过的句子列表。

你方便的话，也许可以做一个 PR 试试看？
