### ISSUE TITLE
大概率性500

### ISSUE THREAD

**Issue by lovelyxmj** [hitokoto-osc/hitokoto-api#98]
我在尝试调用APi时，有几率发生500，并且大多发生在20：00以后，国内与国际都一样，以下为错误截图
![image](https://user-images.githubusercontent.com/53249654/88554027-91339e00-d058-11ea-946b-62dfab88c38f.png)

**Comment by greenhat616** [comment]
如果现在仍有 500 的话可以在此问题继续反馈

**Comment by lovelyxmj** [comment]
好像没有了

**Comment by greenhat616** [comment]
ok，那先关闭了
